### PR TITLE
fix: giscus theme not switched correctly

### PR DESCRIPTION
**Pull request by kowyo**
## 📝 描述

See #190

### CODE REVIEW

**Comment by longlin10086** [comment]
Seems not work on the preview page

**Comment by kowyo** [comment]
https://github.com/user-attachments/assets/aecd2f5e-aedb-49c5-a94b-8effb8848b07

Looks good to me on local server.

**Comment by longlin10086** [comment]
> 20241201-1203-13.1652181.mp4 
> Looks good to me on local server.

When you using darkmode for the first time to visit the website, the comment style will stay light theme.

**Comment by kowyo** [comment]
Do you check https://fix-theme-toggle.hitsz-open-auto-github-io.pages.dev/ ? Can you provide steps to reproduce or record a video?

**Comment by longlin10086** [comment]
> Do you check https://fix-theme-toggle.hitsz-open-auto-github-io.pages.dev/ ? Can you provide steps to reproduce or record a video?

[录屏2024-12-01 20.15.13.zip](https://github.com/user-attachments/files/17968862/2024-12-01.20.15.13.zip)

**Comment by kowyo** [comment]
I cannot reproduce it. Try clean cache of the browser and open it in a private window.

**Comment by longlin10086** [comment]
> https://fix-theme-toggle.hitsz-open-auto-github-io.pages.dev

Still get the current issue.

**Comment by kowyo** [comment]
> > Do you check https://fix-theme-toggle.hitsz-open-auto-github-io.pages.dev/ ? Can you provide steps to reproduce or record a video?
> 
> [录屏2024-12-01 20.15.13.zip](https://github.com/user-attachments/files/17968862/2024-12-01.20.15.13.zip)

when switching theme in the home page, then go to about page, I can reproduce it.

**Comment by kowyo** [comment]
This PR still fixes the issue that theme of giscus not toggled correctly in the same page


https://github.com/user-attachments/assets/0ff2bac9-55c4-4f2b-9fb1-29d331977e21

**Comment by longlin10086** [comment]
I guess I have found the way to fix it.

**Comment by kowyo** [comment]
Works for me. You can approve it and merge it.

**Review by longlin10086 — APPROVED** [review]

**Pull request merged**
